package constants

const (
	PATH_STRAPI_ADVISOR             = "PATH_STRAPI_ADVISOR"
	HOST_STRAPI_SERVICE             = "HOST_STRAPI_SERVICE"
	PATH_STRAPI_INFORMATION_GATEWAY = "PATH_STRAPI_INFORMATION_GATEWAY"
)
