definitions:
  model.ResponseAdvisor:
    properties:
      data:
        $ref: '#/definitions/model.advisorData'
      meta:
        $ref: '#/definitions/model.pagination'
    type: object
  model.ResponseAdvisors:
    properties:
      data:
        items:
          $ref: '#/definitions/model.advisorData'
        type: array
      meta:
        $ref: '#/definitions/model.pagination'
    type: object
  model.ResponseFail:
    properties:
      data: {}
      error:
        $ref: '#/definitions/model.error'
    type: object
  model.advisorData:
    properties:
      SEO:
        $ref: '#/definitions/model.seo'
      active:
        type: boolean
      attachment:
        items:
          $ref: '#/definitions/model.thumbnailLarge'
        type: array
      categories:
        items:
          $ref: '#/definitions/model.categories'
        type: array
      content:
        type: string
      createdAt:
        type: string
      dob:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      job_title:
        type: string
      locale:
        type: string
      publishedAt:
        type: string
      quip:
        type: string
      short_content:
        type: string
      slug:
        type: string
      telephone:
        type: string
      thumbnail:
        $ref: '#/definitions/model.thumbnailLarge'
      updatedAt:
        type: string
    type: object
  model.categories:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      locale:
        type: string
      name:
        type: string
      publishedAt:
        type: string
      slug:
        type: string
      updatedAt:
        type: string
    type: object
  model.error:
    properties:
      details: {}
      message:
        type: string
      name:
        type: string
      status:
        type: integer
    type: object
  model.formatAttribute:
    properties:
      ext:
        type: string
      hash:
        type: string
      height:
        type: integer
      mime:
        type: string
      name:
        type: string
      path:
        type: string
      size:
        type: number
      url:
        type: string
      width:
        type: integer
    type: object
  model.pagination:
    properties:
      pagination:
        $ref: '#/definitions/model.paginationContent'
    type: object
  model.paginationContent:
    properties:
      page:
        type: integer
      pageCount:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  model.seo:
    properties:
      id:
        type: integer
      keywords:
        type: string
      metaDescription:
        type: string
      metaTitle:
        type: string
      preventIndexing:
        type: boolean
      shareImage:
        $ref: '#/definitions/model.seoShareImage'
    type: object
  model.seoShareImage:
    properties:
      alt:
        type: string
      id:
        type: integer
      media:
        $ref: '#/definitions/model.thumbnailLarge'
    type: object
  model.thumbnailLarge:
    properties:
      alternativeText:
        type: string
      caption:
        type: string
      createdAt:
        type: string
      ext:
        type: string
      formats:
        $ref: '#/definitions/model.thumbnailLargeFormat'
      hash:
        type: string
      height:
        type: integer
      id:
        type: integer
      mime:
        type: string
      name:
        type: string
      previewUrl:
        type: string
      provider:
        type: string
      provider_metadata:
        type: string
      size:
        type: number
      updatedAt:
        type: string
      url:
        type: string
      width:
        type: integer
    type: object
  model.thumbnailLargeFormat:
    properties:
      large:
        $ref: '#/definitions/model.formatAttribute'
      medium:
        $ref: '#/definitions/model.formatAttribute'
      small:
        $ref: '#/definitions/model.formatAttribute'
      thumbnail:
        $ref: '#/definitions/model.formatAttribute'
      xsmall:
        $ref: '#/definitions/model.formatAttribute'
    type: object
info:
  contact: {}
paths:
  /advisor-listener/api/advisors:
    get:
      consumes:
      - application/json
      description: Advisor Listener for the service
      operationId: AdvisorListenerHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseAdvisors'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseFail'
      summary: Advisor Listener
      tags:
      - advisor
  /advisor-listener/api/advisors/:id:
    get:
      consumes:
      - application/json
      description: Advisor Listener for the service
      operationId: AdvisorListenerIdHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseAdvisor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseFail'
      summary: Advisor Listener
      tags:
      - advisor
  /advisor-listener/api/advisors/slug/:slug:
    get:
      consumes:
      - application/json
      description: Advisor Listener for the service
      operationId: AdvisorListenerSlugHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseAdvisors'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseFail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseFail'
      summary: Advisor Listener
      tags:
      - advisor
  /healthcheck:
    get:
      description: Health checking for the service
      operationId: HealthCheckHandler
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
swagger: "2.0"
